version: "3.3"

services:
  arbackend:
    build: .
    restart: always
    image: fapsdemonstratorarbackend_arbackend:latest
    environment:
      - PORT:8095
    ports:
      - "8095:8095"
    networks: 
      - backend
    deploy:
      mode: replicated
      replicas: 1

networks:
  backend:
    driver: "overlay"
    attachable: true
