version: "3.3"

services:
  service:
    build: .
    restart: always
    image: fapsdemonstratorarbackend_service_1:latest
    environment:
      - PORT:8090
    ports:
      - "8090:8090"
    networks: 
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.hostname == ontologie


networks:
  backend:
    driver: "overlay"
    attachable: true
