version: "3.3"

services:
  back:
    build: .
    restart: always
    image: fapsdemonstratorarbackend_back:latest
    environment:
      - PORT:8090
    ports:
      - "8090:8090"
    networks: 
      - arbackend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.hostname == ontologie


networks:
  arbackend:
    driver: "overlay"
    attachable: true
